'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const src=fs.readFileSync(path.join(__dirname,'..','app.js'),'utf8');
let p=0,f=0;function ok(c,n,d=''){if(c){console.log('PASS - '+n);p++}else{console.error('FAIL - '+n+(d?' :: '+d:''));f++}}
function extractFunction(text,name){let i=text.indexOf('function '+name+'(');if(i<0)return null;let b=text.indexOf('{',i),d=0,sq=false,dq=false,tq=false,esc=false,line=false,block=false;for(let j=b;j<text.length;j++){let c=text[j],n=text[j+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(sq||dq||tq){if(esc){esc=false;continue}if(c==='\\'){esc=true;continue}if((sq&&c==="'")||(dq&&c==='"')||(tq&&c==='`'))sq=dq=tq=false;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==="'"){sq=true;continue}if(c==='"'){dq=true;continue}if(c==='`'){tq=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(i,j+1)}return null}
const names=['providerNameFromSourceV51','providerQualityV51','providerFallbackUsedV51','sourceQualityForV51','providerQualitySummaryV51','confidenceLabelV51','agreementScoreV51','weightedMetaScoreV51','countrySourceQualityV51','countryFrequencyScoreV51','countryRevisionScoreV51','confidenceCompositeV51','countryConfidenceV51','globalMetaWeightedV51','globalConfidenceV51','freshnessUsableV50','countryCoverageV50','earlyFreshRatioV50','countryFreshRatioV50','globalRiskModel'];
let code='';for(const n of names){let x=extractFunction(src,n);if(!x)throw new Error('missing '+n);code+=x+'\n'}
const providerHealth={FRED:{success:1,fail:0,sourceQuality:'A'},'Yahoo Finance':{success:1,fail:0,sourceQuality:'B'},'World Bank':{success:1,fail:0,sourceQuality:'A'}};
const ctx={console,Math,Number,String,Object,Array,RegExp,providerHealth,
 SOURCE_QUALITY_V51:{'FRED':{grade:'A',score:100,sourceClass:'PRIMARY_OFFICIAL'},'World Bank':{grade:'A',score:100,sourceClass:'PRIMARY_OFFICIAL'},'Yahoo Finance':{grade:'B',score:80,sourceClass:'PRIMARY_MARKET'},'Secondary':{grade:'C',score:60,sourceClass:'SECONDARY'},'Unknown':{grade:'D',score:35,sourceClass:'UNOFFICIAL_FALLBACK'},'Zagreb Stock Exchange':{grade:'A',score:100,sourceClass:'PRIMARY_MARKET'}},
 CONFIDENCE_WEIGHTS_V51:{coverage:30,freshness:20,factorDiversity:15,sourceQuality:15,agreement:8,frequency:6,revision:6},
 GLOBAL_FREQUENCY_V51:{creditFunding:85,volatility:100,equity:100,macro:65,liquidity:90,rates:90,fx:100,commodities:90,correlation:100},GLOBAL_REVISION_V51:{creditFunding:85,volatility:95,equity:95,macro:60,liquidity:85,rates:90,fx:95,commodities:85,correlation:95},
 GLOBAL_WEIGHTS:{creditFunding:25,volatility:15,equity:10,macro:15,liquidity:10,rates:8,fx:7,commodities:5,correlation:5},COUNTRY_MIN_EFFECTIVE_COVERAGE_V50:50,COUNTRY_MIN_FACTOR_GROUPS_V50:3,COUNTRY_FACTOR_GROUPS_V50:{market:['market','technical'],macro:['macro'],credit:['credit'],liquidity:['liquidity'],valuation:['valuation'],systemic:['systemic']},GLOBAL_MIN_EFFECTIVE_COVERAGE_V50:50,GLOBAL_MIN_FACTOR_GROUPS_V50:5,
 avg:a=>{let v=(a||[]).filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null},clamp:x=>Math.max(0,Math.min(100,x)),getWeights:()=>({market:25,macro:20,credit:15,liquidity:15,valuation:10,technical:10,systemic:5})};
vm.createContext(ctx);vm.runInContext(code+';this.pq=providerQualityV51;this.sq=sourceQualityForV51;this.cc=countryCoverageV50;this.cconf=countryConfidenceV51;this.gconf=globalConfidenceV51;this.gr=globalRiskModel;',ctx);
ok(ctx.pq('FRED').grade==='A','official provider class A');ok(ctx.pq('Yahoo Finance').grade==='B','market aggregator class B');ok(ctx.pq('Secondary').grade==='C','secondary provider class C');ok(ctx.pq('Unknown').grade==='D','unknown/unofficial class D');
let sq0=ctx.sq('Yahoo Finance');providerHealth['Yahoo Finance'].cacheStale=true;let sq1=ctx.sq('Yahoo Finance');ok(sq1.score<sq0.score&&sq1.fallbackUsed===true,'stale fallback lowers source quality without deleting data');providerHealth['Yahoo Finance'].cacheStale=false;providerHealth['Yahoo Finance'].fallbackUsed=false;
function mk(subs,fresh,raw={available:8,expected:8},code='US',source='Yahoo Finance'){let c={code,subscores:subs,factorFreshnessV50:fresh,rawCoverageV50:raw,quality:{source}};c.coverageV50=ctx.cc(c);return c}
let c=mk({market:40,macro:42,credit:41,liquidity:39,valuation:43,technical:40,systemic:41},{market:'CURRENT',macro:'CURRENT',credit:'CURRENT',liquidity:'CURRENT',valuation:'CURRENT',technical:'CURRENT',systemic:'CURRENT'});let conf=ctx.cconf(c);ok(c.coverageV50.eligible&&conf.label==='HIGH','complete coherent country => HIGH confidence',JSON.stringify(conf));
let limited=mk({market:72,macro:null,credit:null,liquidity:null,valuation:null,technical:70,systemic:null},{market:'CURRENT',technical:'CURRENT'},{available:2,expected:8});let lc=ctx.cconf(limited);ok(lc.label==='LIMITED','Phase-2 ineligible country => LIMITED confidence');ok(limited.subscores.market===72,'confidence does not mutate risk inputs');
let mixed=mk({market:72,macro:20,credit:80,liquidity:15,valuation:null,technical:70,systemic:30},{market:'CURRENT',macro:'OLD_BUT_CURRENT_RELEASE',credit:'CURRENT',liquidity:'CURRENT',technical:'CURRENT',systemic:'CURRENT'},{available:7,expected:8},'US','Yahoo Finance');let mc=ctx.cconf(mixed);ok(['HIGH','MEDIUM','LOW'].includes(mc.label)&&mc.label!=='LIMITED','eligible country confidence remains separate categorical label');ok(mc.components.agreement<100,'factor disagreement reduces confidence component');
const countries=[{subscores:{market:30,macro:35,liquidity:25,systemic:20},factorFreshnessV50:{market:'CURRENT',macro:'CURRENT',liquidity:'CURRENT',systemic:'CURRENT'}}];
const early=[{name:'HY OAS',trend:'Credit',score:30,freshness:'CURRENT'},{name:'VIX',trend:'Volatility',score:25,freshness:'CURRENT'},{name:'Yield curve',trend:'Rates',score:20,freshness:'CURRENT'},{name:'Trade signal',trend:'Trade',score:35,freshness:'CURRENT'},{name:'Inflation Detector Composite',trend:'Macro',score:40,freshness:'CURRENT'},{name:'Financial stress',trend:'Financial stress',score:25,freshness:'CURRENT'},{name:'Oil risk',trend:'Commodity',score:45,freshness:'CURRENT'}];
const cross={components:{creditFunding:30,breadth:25,optionsStress:20,breadthStress:35,rates:30,fxStress:25,commodity:40,hedgeStress:30}};
let g=ctx.gr(countries,early,cross,{average:.4},20);ok(Number.isFinite(g.score),'GLOBAL risk score still computed');ok(g.confidenceV51&&['HIGH','MEDIUM','LOW','LIMITED'].includes(g.confidence),'GLOBAL confidence object is separate');
let gp=ctx.gr([{subscores:{market:30,macro:null,liquidity:null,systemic:null},factorFreshnessV50:{market:'CURRENT'}}],[],null,{average:null},null);ok(gp.eligible===false&&gp.confidence==='LIMITED','partial GLOBAL remains LIMITED and confidence is LIMITED');ok(gp.score!==0,'missing GLOBAL data never becomes zero risk');
const scoreBefore=g.score;providerHealth.FRED.fallbackUsed=true;let g2=ctx.gr(countries,early,cross,{average:.4},20);ok(g2.score===scoreBefore,'provider quality/fallback does not alter GLOBAL risk score');ok(g2.confidenceV51.sourceQuality.fallbackUsed===true,'GLOBAL confidence records fallback use');
for(const token of ['modelConfidenceV51','sourceQuality','fallbackUsed','Confidence model (separate from risk)','CONFIDENCE_WEIGHTS_V51','HIGH / MEDIUM / LOW / LIMITED'])ok(src.includes(token),'Phase-3 token present: '+token);
ok(src.includes("Risk score and confidence are separate"),'UI explains risk/confidence separation');
ok(src.includes('sourceQuality:e.sourceQuality')&&src.includes('confidenceComponents'),'audit export includes source quality/confidence components');
console.log(`RESULT - ${p}/${p+f} Phase 3 confidence checks PASS`);if(f)process.exit(1);
