from pathlib import Path
checks=[]
def ck(name,v): checks.append((name,bool(v))); print(('PASS ' if v else 'FAIL ')+name)
root=Path('.')
db=(root/'app/src/main/java/com/marko/marketrisk/globalplus/RiskDatabase.java').read_text()
main=(root/'app/src/main/java/com/marko/marketrisk/globalplus/MainActivity.java').read_text()
worker=(root/'app/src/main/java/com/marko/marketrisk/globalplus/BackgroundRefreshWorker.java').read_text()
gradle=(root/'app/build.gradle').read_text()
ck('release identity 2026.09.26.1/124', 'versionCode 124' in gradle and "versionName '2026.09.26.1'" in gradle)
ck('DB schema v4', 'DB_VERSION = 4' in db)
for t in ['calculation_snapshot','observation_revision','change_event','alert_rule','alert_event']: ck('DB table '+t, t in db)
ck('upgrade is additive v4 gate', 'if (oldVersion < 4)' in db and 'createV4Tables(db)' in db)
ck('typed market/data notification channels', 'market_risk_alerts' in main and 'data_health_alerts' in main and 'notifyUserTyped' in main)
ck('native calculation snapshot bridge', 'persistCalculationSnapshot' in main and 'loadCalculationSnapshots' in main)
ck('native change/alert bridge', 'persistChangeEvents' in main and 'persistAlertEvents' in main)
ck('background explicitly prefetch only', 'HTTP_PREFETCH_ONLY' in main and 'HTTP_PREFETCH_ONLY' in worker)
ck('background endpoint diagnostics', 'lastEndpointResults' in worker and 'latencyMs' in worker and 'endpointResults' in main)
ck('worker does not reference GA2 calculation', 'globalRiskModel' not in worker and 'GA2' not in worker)
print(f'RESULT {sum(v for _,v in checks)}/{len(checks)} PASS')
raise SystemExit(0 if all(v for _,v in checks) else 1)
