'use strict';
const fs=require('fs'),crypto=require('crypto'),path=require('path');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'app.js'),'utf8'),base=fs.readFileSync(path.join(root,'app_v35152_baseline.js'),'utf8'),html=fs.readFileSync(path.join(root,'app/src/main/assets/index.html'),'utf8'),gradle=fs.readFileSync(path.join(root,'app/build.gradle'),'utf8'),release=fs.readFileSync(path.join(root,'build_release.sh'),'utf8');
let p=0,f=0;function ok(c,n,d=''){if(c){console.log('PASS - '+n);p++}else{console.error('FAIL - '+n+(d?' :: '+d:''));f++}}function sha(x){return crypto.createHash('sha256').update(x||'').digest('hex')}
function extractFunction(text,name){let i=text.indexOf('function '+name+'(');if(i<0)return null;let b=text.indexOf('{',i),d=0,sq=false,dq=false,tq=false,esc=false,line=false,block=false;for(let j=b;j<text.length;j++){let c=text[j],n=text[j+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(sq||dq||tq){if(esc){esc=false;continue}if(c==='\\'){esc=true;continue}if((sq&&c==="'")||(dq&&c==='"')||(tq&&c==='`'))sq=dq=tq=false;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==="'"){sq=true;continue}if(c==='"'){dq=true;continue}if(c==='`'){tq=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(i,j+1)}return null}
const protectedFns=['riskBand','weightedScore','globalContagion','marketMetrics','trendRisk','macroRiskFromWB','fxRisk','systemScoreForCountry','corrMatrix','correlationRegimeFromStats','correlationRegimeDiagnostic','weightedAvailable','inflationDetector','recessionLeadingAndComposite','buildMacroCycle','fiscalScoreRowsV43','fiscalFreshnessV44','fiscalPickReferenceV44','commodityShockRisk','buildCommodityIntelligence','equityInternalsRecord','aggregateEquityInternalsV42','sp500HiddenWeakness','companyCoreRiskParts','companyContextRisk','loadPriorityForV44','pumpLoadSchedulerV44','queueLoadV44','scheduleDeferredV44','scheduleAroundPageV44','refreshActiveV44','sparklineSvg','marketCardSparkPeriodV46','fetchWithTimeout','freshnessModelV49','freshnessFieldsV49','annotateMacroCycleFreshnessV49','countryCoverageV50','countryConfidenceV51','globalConfidenceV51','providerQualityV51','confidenceCompositeV51','usEarly','completeEarly','enrichEarlySources','earlyClassMetaV52','earlySignalClassificationV52','earlyDisplayRowsV52','earlyClassScoreV52','earlyWarningLayersV52','buildCrossAsset','finalizeCrossAsset'];
for(const n of protectedFns){let a=extractFunction(base,n),b=extractFunction(src,n);ok(!!a&&!!b&&a===b,'protected unchanged: '+n,a&&b?sha(a).slice(0,8)+' != '+sha(b).slice(0,8):'missing')}
ok(extractFunction(base,'globalRiskModel')!==extractFunction(src,'globalRiskModel'),'GLOBAL Risk intentionally changed only for Phase-5 factor architecture');
ok(/versionCode\s+86\b/.test(gradle),'versionCode 86');ok(/versionName\s+['"]3\.5\.1\.53['"]/.test(gradle),'versionName 3.5.1.53');ok(html.includes('v3.5.1_53'),'visible header v3.5.1_53');ok(/VERSION_NAME="3\.5\.1\.53"/.test(release),'release script versionName 3.5.1.53');ok(/VERSION_CODE="86"/.test(release),'release script versionCode 86');
const marker="<script>'use strict';",si=html.indexOf(marker),se=html.lastIndexOf('</script>'),embedded=si>=0&&se>si?html.slice(si+8,se):'';ok(embedded===src.trimEnd(),'embedded app.js byte-identical');ok(html.indexOf(marker)===html.lastIndexOf(marker),'application script embedded once');
for(const n of ['factorRecordV53','legacyGlobalRiskV52','globalFactorArchitectureV53'])ok(!!extractFunction(src,n),'Phase-5 function present: '+n);
ok(src.includes('GLOBAL_LEGACY_WEIGHTS_V52')&&src.includes('GLOBAL_FACTOR_WEIGHTS_V53'),'legacy and new weights both retained');ok(src.includes('weightPreservingSplit:true'),'before/after diagnostic marks weight-preserving split');ok(src.includes('factorContributions')&&src.includes('legacyComparison'),'factor contribution and old/new diagnostics exported');ok(src.includes("structuralFinancial:factorRecordV53")&&src.includes("'Structural Financial Vulnerability',0"),'structural vulnerability remains diagnostic-only');
ok(!/fiscalStructural\s*:/.test(src),'Fiscal Stress not prematurely inserted into production GLOBAL factors');
ok((src.match(/fetch\(/g)||[]).length===(base.match(/fetch\(/g)||[]).length,'no additional fetch call sites');
ok(src.includes('COUNTRY_MIN_EFFECTIVE_COVERAGE_V50=50')&&src.includes('GLOBAL_MIN_EFFECTIVE_COVERAGE_V50=50'),'Phase-2 eligibility thresholds retained');ok(extractFunction(base,'countryCoverageV50')===extractFunction(src,'countryCoverageV50'),'country coverage behavior unchanged');ok(extractFunction(base,'confidenceCompositeV51')===extractFunction(src,'confidenceCompositeV51'),'Phase-3 confidence formula unchanged');
ok(src.includes('earlyWarningLayersV52')&&src.includes('hasSingleCompositeScore:false'),'Phase-4 Early Warning semantics retained');
ok(src.includes("code:'HR'")&&!src.includes("code:'BA'")&&!src.includes('SASX-10'),'Croatia retained and Bosnia absent');ok(src.includes('Android.saveExportFile')&&src.includes('saveExportBlobV48'),'native export bridge retained');ok(!/api[_-]?key\s*[:=]\s*['"][A-Za-z0-9_-]{12,}/i.test(src),'no obvious hard-coded API secret added');
console.log(`RESULT - ${p}/${p+f} Phase 5 v3.5.1.53 regression checks ${f?'FAIL':'PASS'}`);if(f)process.exit(1);
