'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'app.js'),'utf8'),base=fs.readFileSync(path.join(root,'app_v35164_baseline.js'),'utf8'),html=fs.readFileSync(path.join(root,'app/src/main/assets/index.html'),'utf8'),gradle=fs.readFileSync(path.join(root,'app/build.gradle'),'utf8'),release=fs.readFileSync(path.join(root,'build_release.sh'),'utf8'),java=fs.readFileSync(path.join(root,'app/src/main/java/com/marko/marketrisk/globalplus/MainActivity.java'),'utf8');
let p=0,f=0;function ok(c,n,d=''){if(c){console.log('PASS - '+n);p++}else{console.error('FAIL - '+n+(d?' :: '+d:''));f++}}
function extractFunction(text,name){let i=text.indexOf('function '+name+'(');if(i<0)i=text.indexOf('async function '+name+'(');if(i<0)return null;let b=text.indexOf('{',i),d=0,sq=false,dq=false,tq=false,esc=false,line=false,block=false;for(let j=b;j<text.length;j++){let c=text[j],n=text[j+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(sq||dq||tq){if(esc){esc=false;continue}if(c==='\\'){esc=true;continue}if((sq&&c==="'")||(dq&&c==='"')||(tq&&c==='`'))sq=dq=tq=false;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==="'"){sq=true;continue}if(c==='"'){dq=true;continue}if(c==='`'){tq=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(i,j+1)}return null}
function objConst(name){let m=src.match(new RegExp('const '+name+'=({[^;]+});'));return m?Function('return '+m[1])():null}
ok(/versionCode\s+100\b/.test(gradle),'versionCode 98');ok(/versionName\s+['"]3\.5\.1\.67['"]/.test(gradle),'versionName 3.5.1.67');ok(html.includes('v3.5.1_67'),'visible version v3.5.1_67');ok(/VERSION_NAME="3\.5\.1\.67"/.test(release)&&/VERSION_CODE="100"/.test(release),'release metadata');ok(java.includes('MarketRiskMonitor/3.5.1.67'),'native UA');ok(src.includes("const EXPORT_V47_VERSION='3.5.1.67',EXPORT_V47_CODE=100"),'export metadata');
let si=html.indexOf('<script>'),se=html.indexOf('</script>',si+8);ok(html.slice(si+8,se)===src,'embedded JS byte-identical');
ok((src.match(/\bfetch\(/g)||[]).length===(base.match(/\bfetch\(/g)||[]).length,'no new raw fetch callsite');ok((src.match(/\bfetch\(/g)||[]).length===6,'raw fetch count 6');
for(const n of ['riskBand','weightedScore','globalRiskModel','globalFactorArchitectureV53','globalContagion','buildMacroCycle','fiscalScoreRowsV43','commodityShockRisk','aggregateEquityInternalsV57','lagAwareCorrMatrixV58','stabilizedBandV63'])ok(extractFunction(src,n)===extractFunction(base,n),'protected pre-Phase15 function unchanged: '+n);
for(const n of ['currentMacroScoreV65','currentGlobalConditionV65','leadingWarningLayerV65','fiscalGlobalStructuralAggregateV65','structuralVulnerabilityLayerV65','contagionAmplifierV65','globalRiskModelV65','safeGlobalRiskModelV65','globalArchitectureMethodologyV65'])ok(!!extractFunction(src,n),'Phase15 helper present: '+n);
ok(src.includes("const GLOBAL_FINAL_ARCHITECTURE_V65='GA2'"),'GA2 methodology id');
let cw=objConst('GLOBAL_CURRENT_WEIGHTS_V65'),ww=objConst('GLOBAL_WARNING_WEIGHTS_V65'),sw=objConst('GLOBAL_STRUCTURAL_WEIGHTS_V65'),lw=objConst('GLOBAL_LAYER_COVERAGE_WEIGHTS_V65');ok(Object.values(cw).reduce((a,b)=>a+b,0)===95,'current-condition legacy budget excluding correlation =95');ok(!('correlationContagion' in cw),'correlation excluded from base condition');ok(cw.currentMacro===15,'macro+inflation legacy budget consolidated to 15');ok(ww.leading===70&&ww.earlyConfirmation===30,'warning 70/30');ok(!('lateConfirmation' in ww),'late confirmation not weighted into warning');ok(sw.fiscal===50&&sw.financial===50,'structural 50/50');ok(Object.values(lw).reduce((a,b)=>a+b,0)===100,'layer coverage weights sum 100');
ok(src.includes('GLOBAL_FISCAL_GDP_CAP_V65=.35'),'fiscal GDP cap 35%');ok(src.includes('nominalGdpUsd')&&src.includes('cappedNormalizeV57'),'GDP weighting and cap used');ok(src.includes('scopeComparableV60')&&src.includes('structuralEligibleV60'),'fiscal comparability eligibility retained');
ok(src.includes('GLOBAL_WARNING_MAX_ADD_V65=10'),'warning add capped +10');ok(src.includes('GLOBAL_STRUCTURAL_MAX_ADD_V65=5'),'structural add capped +5');ok(src.includes('GLOBAL_CONTAGION_MAX_MULTIPLIER_V65=1.15'),'contagion cap 1.15');ok(src.includes("rule:'clamp((CurrentCondition + warningAdd + structuralAdd) × bounded Contagion multiplier)'")||src.includes("formula:'clamp((CurrentCondition + warningAdd + structuralAdd) * contagionMultiplier)'"),'final layered formula exported');ok(src.includes("multiplier=1+(GLOBAL_CONTAGION_MAX_MULTIPLIER_V65-1)*activation*pressure"),'amplifier non-negative formulation');
// independent arithmetic fixtures
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));function calc(base,warn,struct,cont){let wa=Number.isFinite(warn)?clamp((warn-45)*.20,0,10):0,sa=Number.isFinite(struct)?clamp((struct-50)*.10,0,5):0,pre=clamp(base+wa+sa),act=clamp((pre-35)/40,0,1),press=clamp((cont-50)/50,0,1),mult=1+.15*act*press;return{wa,sa,pre,mult,score:Math.round(clamp(pre*mult))}}
let a=calc(40,20,20,20);ok(a.wa===0&&a.sa===0&&a.mult===1&&a.score===40,'low warning/structural/contagion cannot reduce current stress');let b=calc(40,95,100,100);ok(b.wa===10&&b.sa===5,'positive add-ons respect caps');ok(b.mult>1&&b.mult<=1.15,'high contagion amplifies but stays capped');ok(b.score>=55,'high layered stress raises final score');let c=calc(80,20,20,0);ok(c.score===80,'low correlation cannot cancel severe current stress');let d=calc(80,20,20,100);ok(d.score>80&&d.score<=92,'contagion amplifies severe stress within cap');
ok(src.includes('ensureFiscalV43(false).catch'),'fiscal structural layer starts resiliently during global refresh');ok(src.includes('safeGlobalRiskModelV65(countries,combinedEarly,crossAsset,corrSystemic,globalMacroCycleV59,fiscalRowsV65)'),'refresh uses GA2 model');ok(src.includes('productionGlobalRiskIntegration:true'),'macro/fiscal integration metadata updated');ok(src.includes('globalFinalArchitectureV65'),'audit metadata exposes GA2');
for(const id of ['global_current_condition_v65','global_leading_warning_v65','global_structural_v65','global_contagion_amplifier_v65','global_final_v65'])ok(src.includes("id:'"+id+"'"),'score transform registry: '+id);
ok(src.includes('finalArchitectureVersion:g.architectureVersion'),'PIT snapshot stores final architecture version');ok(src.includes('finalLayers:g.layersV65'),'PIT snapshot stores final layers');ok(src.includes('finalFormula:g.formulaV65'),'PIT snapshot stores final formula');ok(src.includes('Phase 15 — Final GLOBAL Risk Architecture'),'methodology export documents Phase15');
console.log(`RESULT - ${p}/${p+f} PASS`);if(f)process.exit(1);
