'use strict';
const fs=require('fs'),crypto=require('crypto'),path=require('path'),vm=require('vm');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'app.js'),'utf8'),base=fs.readFileSync(path.join(root,'app_v35150_baseline.js'),'utf8'),html=fs.readFileSync(path.join(root,'app/src/main/assets/index.html'),'utf8'),gradle=fs.readFileSync(path.join(root,'app/build.gradle'),'utf8');
let p=0,f=0;function ok(c,n,d=''){if(c){console.log('PASS - '+n);p++}else{console.error('FAIL - '+n+(d?' :: '+d:''));f++}}
function sha(x){return crypto.createHash('sha256').update(x||'').digest('hex')}
function extractFunction(text,name){let i=text.indexOf('function '+name+'(');if(i<0)return null;let b=text.indexOf('{',i),d=0,sq=false,dq=false,tq=false,esc=false,line=false,block=false;for(let j=b;j<text.length;j++){let c=text[j],n=text[j+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(sq||dq||tq){if(esc){esc=false;continue}if(c==='\\'){esc=true;continue}if((sq&&c==="'")||(dq&&c==='"')||(tq&&c==='`'))sq=dq=tq=false;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==="'"){sq=true;continue}if(c==='"'){dq=true;continue}if(c==='`'){tq=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(i,j+1)}return null}
const protectedFns=['riskBand','weightedScore','globalContagion','marketMetrics','trendRisk','macroRiskFromWB','fxRisk','systemScoreForCountry','corrMatrix','correlationRegimeFromStats','correlationRegimeDiagnostic','weightedAvailable','inflationDetector','recessionLeadingAndComposite','buildMacroCycle','fiscalScoreRowsV43','fiscalFreshnessV44','fiscalPickReferenceV44','commodityShockRisk','buildCommodityIntelligence','equityInternalsRecord','aggregateEquityInternalsV42','sp500HiddenWeakness','companyCoreRiskParts','companyContextRisk','loadPriorityForV44','pumpLoadSchedulerV44','queueLoadV44','scheduleDeferredV44','scheduleAroundPageV44','refreshActiveV44','sparklineSvg','marketCardSparkPeriodV46','fetchWithTimeout','freshnessModelV49','freshnessFieldsV49','annotateMacroCycleFreshnessV49','countryCoverageV50'];
for(const n of protectedFns){const a=extractFunction(base,n),b=extractFunction(src,n);ok(!!a&&!!b&&a===b,'protected unchanged: '+n,a&&b?sha(a).slice(0,8)+' != '+sha(b).slice(0,8):'missing')}
ok(/versionCode\s+84\b/.test(gradle),'versionCode 84');ok(/versionName\s+['"]3\.5\.1\.51['"]/.test(gradle),'versionName 3.5.1.51');ok(html.includes('v3.5.1_51'),'visible header v3.5.1_51');
const marker="<script>'use strict';",si=html.indexOf(marker),se=html.lastIndexOf('</script>'),embedded=si>=0&&se>si?html.slice(si+8,se):'';ok(embedded===src.trimEnd(),'embedded app.js byte-identical');ok(html.indexOf(marker)===html.lastIndexOf(marker),'application script embedded once');
for(const n of ['countryConfidenceV51','globalConfidenceV51','providerQualityV51','confidenceCompositeV51'])ok(!!extractFunction(src,n),'Phase-3 function present: '+n);
ok(src.includes("code:'HR'")&&!src.includes("code:'BA'")&&!src.includes('SASX-10'),'Croatia retained and Bosnia absent');ok(src.includes('Android.saveExportFile')&&src.includes('saveExportBlobV48'),'native export bridge retained');ok(src.includes('COUNTRY_MIN_EFFECTIVE_COVERAGE_V50=50')&&src.includes('GLOBAL_MIN_EFFECTIVE_COVERAGE_V50=50'),'Phase-2 eligibility gates retained');
// Global score invariance against v50 using identical finite inputs. New confidence helper is stubbed so only score path is compared.
const oldGR=extractFunction(base,'globalRiskModel'),newGR=extractFunction(src,'globalRiskModel');const gw={creditFunding:25,volatility:15,equity:10,macro:15,liquidity:10,rates:8,fx:7,commodities:5,correlation:5};const avg=a=>{let v=(a||[]).filter(Number.isFinite);return v.length?v.reduce((x,y)=>x+y,0)/v.length:null},clamp=x=>Math.max(0,Math.min(100,x));const countries=[{subscores:{market:30,macro:35,liquidity:25,systemic:20},factorFreshnessV50:{market:'CURRENT',macro:'CURRENT',liquidity:'CURRENT',systemic:'CURRENT'}}],early=[{name:'HY OAS',trend:'Credit',score:30,freshness:'CURRENT'},{name:'VIX',trend:'Volatility',score:25,freshness:'CURRENT'},{name:'Yield curve',trend:'Rates',score:20,freshness:'CURRENT'},{name:'Trade signal',trend:'Trade',score:35,freshness:'CURRENT'},{name:'Inflation Detector Composite',trend:'Macro',score:40,freshness:'CURRENT'},{name:'Financial stress',trend:'Financial stress',score:25,freshness:'CURRENT'},{name:'Oil risk',trend:'Commodity',score:45,freshness:'CURRENT'}],cross={components:{creditFunding:30,breadth:25,optionsStress:20,breadthStress:35,rates:30,fxStress:25,commodity:40,hedgeStress:30}};
let common={console,Math,Number,String,Object,Array,RegExp,GLOBAL_WEIGHTS:gw,GLOBAL_MIN_EFFECTIVE_COVERAGE_V50:50,GLOBAL_MIN_FACTOR_GROUPS_V50:5,providerHealth:{FRED:{success:1},Yahoo:{success:1}},avg,clamp,freshnessUsableV50:x=>x==='CURRENT'||x==='OLD_BUT_CURRENT_RELEASE',earlyFreshRatioV50:r=>{let x=(r||[]).filter(z=>Number.isFinite(z.score));return x.length?x.filter(z=>['CURRENT','OLD_BUT_CURRENT_RELEASE'].includes(z.freshnessStatus||z.freshness)).length/x.length:null},countryFreshRatioV50:(cs,k)=>{let x=(cs||[]).filter(c=>Number.isFinite(c.subscores&&c.subscores[k]));return x.length?avg(x.map(c=>['CURRENT','OLD_BUT_CURRENT_RELEASE'].includes(c.factorFreshnessV50&&c.factorFreshnessV50[k])?1:0)):null}};
let c0={...common};vm.createContext(c0);vm.runInContext(oldGR+';this.g=globalRiskModel;',c0);let a=c0.g(countries,early,cross,{average:.4},20);let c1={...common,globalConfidenceV51:()=>({score:77,label:'MEDIUM',components:{},sourceQuality:{}})};vm.createContext(c1);vm.runInContext(newGR+';this.g=globalRiskModel;',c1);let b=c1.g(countries,early,cross,{average:.4},20);ok(a.score===b.score,'GLOBAL numeric risk score identical to v50',a.score+' vs '+b.score);ok(JSON.stringify(a.components)===JSON.stringify(b.components),'GLOBAL component scores identical to v50');
ok(extractFunction(base,'fetchWithTimeout')===extractFunction(src,'fetchWithTimeout'),'no network-request architecture change');ok((src.match(/fetch\(/g)||[]).length===(base.match(/fetch\(/g)||[]).length,'no additional fetch call sites');
console.log(`RESULT - ${p}/${p+f} Phase 3 v3.5.1.51 regression checks PASS`);if(f)process.exit(1);
