'use strict';
const fs=require('fs'),path=require('path');
const root=path.join(__dirname,'..'),src=fs.readFileSync(path.join(root,'app.js'),'utf8'),base=fs.readFileSync(path.join(root,'app_v35165_baseline.js'),'utf8'),html=fs.readFileSync(path.join(root,'app/src/main/assets/index.html'),'utf8'),gradle=fs.readFileSync(path.join(root,'app/build.gradle'),'utf8'),release=fs.readFileSync(path.join(root,'build_release.sh'),'utf8'),java=fs.readFileSync(path.join(root,'app/src/main/java/com/marko/marketrisk/globalplus/MainActivity.java'),'utf8');
let p=0,f=0;function ok(c,n,d=''){if(c){console.log('PASS - '+n);p++}else{console.error('FAIL - '+n+(d?' :: '+d:''));f++}}
function extractFunction(text,name){let i=text.indexOf('function '+name+'(');if(i<0)return null;let b=text.indexOf('{',i),d=0,sq=false,dq=false,tq=false,escp=false,line=false,block=false;for(let j=b;j<text.length;j++){let c=text[j],n=text[j+1];if(line){if(c==='\n')line=false;continue}if(block){if(c==='*'&&n==='/'){block=false;j++}continue}if(sq||dq||tq){if(escp){escp=false;continue}if(c==='\\'){escp=true;continue}if((sq&&c==="'")||(dq&&c==='"')||(tq&&c==='`'))sq=dq=tq=false;continue}if(c==='/'&&n==='/'){line=true;j++;continue}if(c==='/'&&n==='*'){block=true;j++;continue}if(c==="'"){sq=true;continue}if(c==='"'){dq=true;continue}if(c==='`'){tq=true;continue}if(c==='{')d++;else if(c==='}'&&--d===0)return text.slice(i,j+1)}return null}
function objConst(text,name){let m=text.match(new RegExp('const '+name+'=({[^;]+});'));return m?Function('return '+m[1])():null}
// release identity and parity
ok(/versionCode\s+99\b/.test(gradle),'versionCode 99');ok(/versionName\s+['"]3\.5\.1\.66['"]/.test(gradle),'versionName 3.5.1.66');ok(html.includes('v3.5.1_66'),'visible header v3.5.1_66');ok(/VERSION_NAME="3\.5\.1\.66"/.test(release)&&/VERSION_CODE="99"/.test(release),'release metadata 3.5.1.66 / 99');ok(java.includes('MarketRiskMonitor/3.5.1.66'),'native UA v3.5.1.66');ok(src.includes("const EXPORT_V47_VERSION='3.5.1.66',EXPORT_V47_CODE=99"),'export metadata 3.5.1.66 / 99');
let si=html.indexOf('<script>'),se=html.indexOf('</script>',si+8);ok(html.slice(si+8,se)===src,'embedded WebView JS byte-identical to app.js');ok((src.match(/\bfetch\(/g)||[]).length===(base.match(/\bfetch\(/g)||[]).length,'Phase16 adds no raw fetch callsite');ok((src.match(/\bfetch\(/g)||[]).length===6,'raw fetch count remains 6');
// Phase16 must not change production/model arithmetic.
for(const n of ['riskBand','weightedScore','globalRiskModel','globalFactorArchitectureV53','globalContagion','buildMacroCycle','fiscalScoreRowsV43','commodityShockRisk','aggregateEquityInternalsV57','lagAwareCorrMatrixV58','stabilizedBandV63','currentMacroScoreV65','currentGlobalConditionV65','leadingWarningLayerV65','fiscalGlobalStructuralAggregateV65','structuralVulnerabilityLayerV65','contagionAmplifierV65','globalRiskModelV65','safeGlobalRiskModelV65'])ok(extractFunction(src,n)===extractFunction(base,n),'scoring/model function unchanged: '+n);
for(const n of ['globalUiLabelV66','globalCurrentDriverRowsV66','globalExplanationDataV66','signedV66','globalLayerRowsV66','globalLayerSummaryHtmlV66','globalDriverRowHtmlV66','globalRiskDriversHtmlV66','globalExplanationHtmlV66'])ok(!!extractFunction(src,n),'Phase16 presentation helper present: '+n);
ok(src.includes("const GLOBAL_UI_EXPLANATION_METHOD_V66='UI-EXPLAIN-V1'"),'deterministic UI explanation methodology id');
for(const id of ['globalRegimeDetailV66','globalLayerSummaryV66','overviewGlobalWhyV66','overviewRiskDrivers'])ok(html.includes('id="'+id+'"'),'Phase16 UI target present: '+id);
ok(html.includes('Current Condition factors'),'risk driver card names production base layer');ok(html.includes('global-layer-strip-v66')&&html.includes('@media(max-width:700px)'),'layer summary has responsive layout');ok(html.includes('global-driver-groups-v66')&&html.includes('global-why-v66'),'deterministic explanation styles present');
ok(src.includes("L('Faktorska pokrivenost','Factor coverage')")&&src.includes("L('Pokrivenost svježinom','Freshness coverage')"),'hero exposes factor and freshness coverage');ok(src.includes("L('GLOBALNI RIZIK','GLOBAL RISK')"),'compact GLOBAL RISK hero label');ok(src.includes("L('Zašto je score ','Why is the score ')")||src.includes('Why is the score'),'Why-is-the-score inspection control');ok(src.includes("L('Najveći risk pressure','Highest risk pressure')")&&src.includes("L('Najveći offset / najniži rizik','Largest offsets / lowest risk')"),'highest and lowest contributors exposed');ok(src.includes('The explanation is generated only from current model values and the fixed GA2 formula.'),'explanation explicitly deterministic/data-driven');
ok(!extractFunction(src,'globalExplanationDataV66').includes('fetch('),'explanation data helper has no network path');ok(!extractFunction(src,'globalExplanationDataV66').includes('Math.random'),'explanation data helper is deterministic');
// Evaluate the pure presentation calculation with a deterministic fixture.
const weights=objConst(src,'GLOBAL_CURRENT_WEIGHTS_V65');const labels=objConst(src,'GLOBAL_CURRENT_LABELS_V66');
let code=`const GLOBAL_CURRENT_WEIGHTS_V65=${JSON.stringify(weights)};const GLOBAL_CURRENT_LABELS_V66=${JSON.stringify(labels)};const GLOBAL_UI_EXPLANATION_METHOD_V66='UI-EXPLAIN-V1';let currentLang='en';const L=(h,e)=>currentLang==='hr'?h:e;`;
for(const n of ['globalUiLabelV66','globalCurrentDriverRowsV66','globalExplanationDataV66','signedV66','globalLayerRowsV66'])code+=extractFunction(src,n)+'\n';code+='return {globalCurrentDriverRowsV66,globalExplanationDataV66,globalLayerRowsV66};';
let api=Function(code)();
let fixture={score:60,band:{label:'ORANGE'},confidence:'MEDIUM',factorCoverage:91,freshnessCoverage:87,effectiveCoverage:84,layersV65:{currentCondition:{score:55,effectiveCoverage:84,weights:{...weights},components:{credit:80,fundingLiquidity:65,volatility:30,equityInternals:40,rates:50,fx:45,currentMacro:70,commodities:55}},leadingWarning:{score:60,coveragePct:100},structuralVulnerability:{score:55,coveragePct:100},contagionAmplifier:{score:70,multiplier:1.05}},formulaV65:{warningAdjustment:3,structuralAdjustment:.5,preAmplifier:58.5,contagionMultiplier:1.05,finalScore:60}};
let a=api.globalExplanationDataV66(fixture),b=api.globalExplanationDataV66(JSON.parse(JSON.stringify(fixture)));
ok(JSON.stringify(a)===JSON.stringify(b),'same model values produce byte-identical explanation data');ok(a.finalScore===60&&a.confidence==='MEDIUM','final score/confidence passed through without recalculation');ok(a.factorCoverage===91&&a.freshnessCoverage===87,'factor/freshness coverage preserved');ok(a.drivers.length===8,'all eight Current Condition factors represented');ok(a.highest[0].key==='credit','highest weighted risk pressure is deterministic');ok(a.lowest[0].key==='volatility','largest weighted offset is deterministic');
let sumEffect=a.drivers.reduce((z,r)=>z+r.weightedEffect,0),weighted=a.drivers.reduce((z,r)=>z+r.score*r.weight,0)/a.drivers.reduce((z,r)=>z+r.weight,0);ok(Math.abs(sumEffect-(weighted-50))<1e-9,'driver effects reconcile exactly to weighted Current Condition deviation from 50');
let layers=api.globalLayerRowsV66(fixture);ok(layers.length===4,'exactly four Phase15 layers shown');ok(layers[0].score===55&&layers[1].score===60&&layers[2].score===55&&layers[3].score===70,'layer scores are presentation pass-through');ok(layers[3].meta==='×1.050','contagion multiplier shown separately from score');ok(api.globalExplanationDataV66({}).drivers.length===0,'missing layer data stays unavailable, not zero-filled');
// Existing Phase15 weights/formula constants remain intact.
ok(Object.values(weights).reduce((x,y)=>x+y,0)===95&&!('correlationContagion' in weights),'Current Condition weight budget unchanged and correlation excluded');ok(src.includes('GLOBAL_WARNING_MAX_ADD_V65=10')&&src.includes('GLOBAL_STRUCTURAL_MAX_ADD_V65=5')&&src.includes('GLOBAL_CONTAGION_MAX_MULTIPLIER_V65=1.15'),'Phase15 caps unchanged');
console.log(`RESULT - ${p}/${p+f} Phase 16 UI/explanation checks PASS`);if(f)process.exit(1);
