from pathlib import Path
import re, sys
ROOT=Path(__file__).resolve().parents[1]
app=(ROOT/'app.js').read_text()
html=(ROOT/'app/src/main/assets/index.html').read_text()
gradle=(ROOT/'app/build.gradle').read_text()
excel=(ROOT/'app/src/main/assets/excel_export_v362.js').read_text()
builder=(ROOT/'tools/build_manual_apk_v365.py').read_text()
checks=[]
def ck(name,ok): checks.append((name,bool(ok)))
ck('release identity 3.6.5/115', "EXPORT_V47_VERSION='3.6.5',EXPORT_V47_CODE=115" in app)
ck('gradle identity 3.6.5/115', re.search(r'versionCode\s+115\b',gradle) and re.search(r'versionName\s+[\"\']3\.6\.5[\"\']',gradle))
ck('excel metadata identity 3.6.5/115', "XLSX_VERSION_V362='3.6.5'" in excel and 'XLSX_VERSION_CODE_V362=115' in excel)
ck('manual builder identity 3.6.5/115', "'3.6.5'" in builder and 'data_val=115' in builder)
st=html.find("<script>'use strict';"); en=html.find('</script>',st)
embedded=html[st+len('<script>'):en] if st>=0 and en>st else ''
ck('runtime embeds canonical app.js', embedded.rstrip('\n')==app.rstrip('\n'))
ck('daily method CR2.0-DAILY', "CAPITAL_ROTATION_METHOD_V70='CR2.0-DAILY'" in app)
ck('SPY benchmark', "CAPITAL_ROTATION_DAILY_BENCHMARK_V115='SPY'" in app)
for sym in ['XLK','XLF','XLE','XLI','XLV','XLU','XLY','XLP','XLC','XLB','XLRE']:
    ck('sector '+sym, f"symbol:'{sym}'" in app)
ck('1D excess weight 45', 'dailyExcessReturn:45' in app)
ck('cross sectional rank weight 20', 'crossSectionRank:20' in app)
ck('volume weight 15', 'volumeConfirmation:15' in app)
ck('breadth weight 10', 'breadthConfirmation:10' in app)
ck('cross asset weight 10', 'crossAssetConfirmation:10' in app)
ck('breadth missing remains N/A', 'breadthConfirmation:null' in app)
ck('5D context calculated separately', 'fiveDayExcess' in app and 'capitalRotationDailyFiveDayContextV115' in app)
ck('daily score status bands', 'STRONG RELATIVE INFLOW' in app and 'STRONG RELATIVE OUTFLOW' in app)
ck('same-date alignment', 'capitalRotationDailyCommonPointsV115' in app)
ck('volume baseline uses prior median', 'medianNumber(priorVol)' in app)
ck('rank changes implemented', 'rankChange' in app)
ck('acceleration implemented', 'acceleration' in app)
ck('reversal implemented', 'POSITIVE REVERSAL' in app and 'NEGATIVE REVERSAL' in app)
ck('daily title visible', 'DAILY CAPITAL ROTATION' in app)
ck('refresh daily rotation visible', 'REFRESH DAILY ROTATION' in app)
ck('5D explicitly context-only in methodology', '5D is context only' in app)
ck('does not call price rotation measured fund flow', 'not measured fund flow' in app)
ck('T212 module remains packaged', '<script src="t212_portfolio_v363.js"></script>' in html)
ck('Excel module remains packaged', '<script src="excel_export_v362.js"></script>' in html)
for name,ok in checks: print(('PASS' if ok else 'FAIL')+' '+name)
print(f'RESULT {sum(ok for _,ok in checks)}/{len(checks)} PASS')
sys.exit(0 if all(ok for _,ok in checks) else 1)
